#!/usr/bin/env python3
"""
BLS Reviewer build script.

Scans data/bls/** JSON files and emits data/bundle.js which assigns the entire
course dataset to window.BLS_DATA. This lets index.html run by double-clicking
(file://) without a web server, while keeping the per-chapter JSON files as the
canonical, app-integration-friendly source of truth.

Also validates: JSON parse, unique IDs, and chapter cross-references.

Usage:  python build.py
"""
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(ROOT, "data", "bls")
TYPES = ["chapters", "flashcards", "quizzes", "scenarios", "algorithms", "tables"]


def load(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def main():
    errors, warnings = [], []
    ids = {}

    manifest_path = os.path.join(DATA, "manifest.json")
    if not os.path.exists(manifest_path):
        print("FATAL: manifest.json not found", file=sys.stderr)
        sys.exit(1)
    manifest = load(manifest_path)
    chapter_ids = [c["id"] for c in manifest["chapters"]]

    dataset = {"manifest": manifest}
    for t in TYPES:
        dataset[t] = {}
        for path in sorted(glob.glob(os.path.join(DATA, t, "c*.json"))):
            cid = os.path.splitext(os.path.basename(path))[0]
            try:
                obj = load(path)
            except Exception as e:
                errors.append(f"{t}/{cid}.json: JSON error: {e}")
                continue
            dataset[t][cid] = obj
            # collect IDs for uniqueness check
            for key in ("cards", "questions", "cases"):
                for item in obj.get(key, []):
                    iid = item.get("id")
                    if not iid:
                        warnings.append(f"{t}/{cid}.json: item missing id")
                        continue
                    if iid in ids:
                        errors.append(f"Duplicate id '{iid}' in {t}/{cid} and {ids[iid]}")
                    ids[iid] = f"{t}/{cid}"

    # coverage report
    print("=== Coverage ===")
    print(f"{'chap':6}", *[f"{t[:4]:>6}" for t in TYPES])
    for cid in chapter_ids:
        row = []
        for t in TYPES:
            obj = dataset[t].get(cid)
            if obj is None:
                row.append("  -  ")
            else:
                n = 0
                for key in ("cards", "questions", "cases", "summary", "algorithms", "tables"):
                    if isinstance(obj.get(key), list):
                        n = len(obj[key])
                        break
                row.append(f"{n:>5}")
        print(f"{cid:6}", *[f"{c:>6}" for c in row])

    out = os.path.join(ROOT, "data", "bundle.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build.py — do not edit. Source: data/bls/**\n")
        f.write("window.BLS_DATA = ")
        json.dump(dataset, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    print(f"\nWrote {out} ({os.path.getsize(out)//1024} KB)")
    if warnings:
        print(f"\n=== {len(warnings)} warnings ===")
        for w in warnings[:40]:
            print("  WARN:", w)
    if errors:
        print(f"\n=== {len(errors)} ERRORS ===")
        for e in errors:
            print("  ERR:", e)
        sys.exit(2)
    print("\nValidation OK.")


if __name__ == "__main__":
    main()
