#!/usr/bin/env node
/*
 * Splits the mega chapter bundles in content/cN.js into a lightweight
 * meta bundle (TOC only, loaded synchronously) + one JSON file per
 * section (fetched on demand when a tab is opened).
 *
 * content/cN.js stays untouched — it remains the offline source of
 * truth and the fallback app.js uses if a per-section fetch fails.
 *
 * Usage: node scripts/split_content.js
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const CONTENT_DIR = path.join(ROOT, 'content');

// Only the multi-section "mega bundle" chapters need splitting.
// c0/m1-38 are single-section (flat) — no per-tab win. c-index.js
// calls generateIndexHTML() at load time and isn't a plain data file.
const CHAPTER_IDS = ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10'];

function loadChapterData(chapterId) {
    const filePath = path.join(CONTENT_DIR, `${chapterId}.js`);
    let src = fs.readFileSync(filePath, 'utf8').replace(/^﻿/, '');
    const sandbox = { window: {}, console };
    vm.createContext(sandbox);
    vm.runInContext(src, sandbox, { filename: filePath });
    const data = sandbox.window.CPG_DATA;
    if (!data || !Array.isArray(data.sections)) {
        throw new Error(`${chapterId}.js did not produce window.CPG_DATA.sections`);
    }
    return data;
}

function main() {
    let totalBefore = 0;
    let totalMetaAfter = 0;

    for (const chapterId of CHAPTER_IDS) {
        const srcPath = path.join(CONTENT_DIR, `${chapterId}.js`);
        const data = loadChapterData(chapterId);
        totalBefore += fs.statSync(srcPath).size;

        const sectionDir = path.join(CONTENT_DIR, chapterId);
        fs.mkdirSync(sectionDir, { recursive: true });

        const metaSections = data.sections.map(function (s) {
            fs.writeFileSync(
                path.join(sectionDir, `${s.id}.json`),
                JSON.stringify({
                    id: s.id,
                    shortTitle: s.shortTitle,
                    summary: s.summary || '',
                    quiz: s.quiz || [],
                    flashcards: s.flashcards || [],
                    critical: s.critical || []
                })
            );
            return { id: s.id, shortTitle: s.shortTitle };
        });

        const meta = {
            id: data.id,
            title: data.title,
            shortTitle: data.shortTitle,
            sections: metaSections
        };

        const metaContent = `/* Auto-generated by scripts/split_content.js — do not hand-edit. */\nwindow.CPG_DATA = ${JSON.stringify(meta)};\n`;
        const metaPath = path.join(CONTENT_DIR, `${chapterId}.meta.js`);
        fs.writeFileSync(metaPath, metaContent);
        totalMetaAfter += metaContent.length;

        console.log(`${chapterId}: ${data.sections.length} sections -> ${sectionDir}/*.json + ${chapterId}.meta.js (${metaContent.length} bytes)`);
    }

    console.log(`\nOriginal bundles: ${(totalBefore / 1024).toFixed(0)} KB total`);
    console.log(`Meta bundles:     ${(totalMetaAfter / 1024).toFixed(0)} KB total (loaded synchronously; sections fetched on demand)`);
}

main();
